#!/usr/bin/env python3
"""Install, upgrade, and validate a portable agent knowledge framework (Python 3.9+)."""

import argparse
import hashlib
import json
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


PACKAGE = Path(__file__).resolve().parent
MARKER = "Generated by .agents/framework/harness.py; edit framework or project sources."
NAME = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
CLAUDE_FIELDS = {"model", "tools", "disallowedTools", "permissionMode", "skills", "maxTurns"}
CODEX_FIELDS = {"model", "model_reasoning_effort", "sandbox_mode"}
CODEX_SETTINGS = {"model", "model_reasoning_effort", "sandbox_mode", "approval_policy", "features"}
GENERATED_LOCK = ".agents/generated.lock.json"
FRAMEWORK_LOCK = ".agents/framework.lock.json"


@dataclass(frozen=True)
class Entry:
    data: bytes = b""
    link: str = ""

    def fingerprint(self):
        if self.link:
            return "link:" + self.link
        return "sha256:" + hashlib.sha256(self.data).hexdigest()


def text_entry(value):
    return Entry(data=value.encode("utf-8"))


def json_text(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def scalar(value):
    if isinstance(value, (str, bool, int)):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return json.dumps(value, ensure_ascii=False)
    raise ValueError("native values must be strings, booleans, integers, or string lists")


def safe_path(root, relative):
    """Do not follow directory symlinks while reading or managing target paths."""
    relative = Path(relative)
    if relative.is_absolute() or ".." in relative.parts or not relative.parts:
        raise ValueError(f"unsafe relative path: {relative}")
    path = root / relative
    for parent in (path, *path.parents):
        if parent == root:
            break
        if parent != path and parent.is_symlink():
            raise ValueError(f"refusing directory symlink: {parent.relative_to(root)}")
    return path


def existing(path):
    if path.is_symlink():
        return Entry(link=path.readlink().as_posix())
    if path.is_file():
        return Entry(data=path.read_bytes())
    if path.exists():
        raise ValueError(f"expected a file or managed symlink: {path}")
    return None


def load_json(path):
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"expected JSON object: {path}")
    return value


def read_source(root, relative, seeds=None):
    path = safe_path(root, relative)
    if path.is_symlink():
        raise ValueError(f"source must not be a symlink: {relative}")
    if seeds and relative in seeds:
        return seeds[relative].data.decode("utf-8")
    return path.read_text(encoding="utf-8")


def generated_path(relative):
    if relative in {"AGENTS.md", "CLAUDE.md", ".mcp.json", ".codex/config.toml",
                    ".codex/hooks.json", ".claude/settings.json", ".claude/skills"}:
        return True
    path = Path(relative)
    return ((path.parent.as_posix(), path.suffix) in
            {(".codex/agents", ".toml"), (".claude/agents", ".md")} or
            path.parent.as_posix() == ".agents/skills")


def plan_managed(root, outputs, lock_name, allowed):
    """Preflight every conflict, including removals, before returning a write plan."""
    lock_path = safe_path(root, lock_name)
    if lock_path.is_symlink():
        raise ValueError(f"lock must not be a symlink: {lock_name}")
    state = load_json(lock_path) if lock_path.exists() else {"schema_version": 1, "files": {}}
    if set(state) != {"schema_version", "files"} or state["schema_version"] != 1:
        raise ValueError(f"unsupported lock format: {lock_name}")
    old = state["files"]
    if not isinstance(old, dict) or not all(isinstance(v, str) for v in old.values()):
        raise ValueError(f"invalid file hashes: {lock_name}")
    changes, errors = {}, []
    for relative in sorted(set(outputs) | set(old)):
        if not allowed(relative):
            raise ValueError(f"path outside managed scope: {relative}")
        path = safe_path(root, relative)
        current = existing(path)
        wanted = outputs.get(relative)
        if current == wanted:
            continue
        if current is not None and current.fingerprint() != old.get(relative):
            errors.append(f"{relative}: local or unowned content conflicts; preserve and migrate it first")
        else:
            changes[relative] = wanted
    if errors:
        raise ValueError("\n".join(errors))
    updated = text_entry(json_text({"schema_version": 1,
                                   "files": {k: v.fingerprint() for k, v in sorted(outputs.items())}}))
    if existing(lock_path) != updated:
        changes[lock_name] = updated
    return changes


def apply_plan(root, changes):
    # Locks are written last. An interrupted run can be retried: exact desired
    # files are accepted even when the old lock has not yet been updated.
    for relative in sorted(changes, key=lambda p: (p.endswith(".lock.json"), p)):
        path = safe_path(root, relative)
        wanted = changes[relative]
        if wanted is None:
            path.unlink()
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        if wanted.link:
            if path.exists():
                path.unlink()
            path.symlink_to(wanted.link, target_is_directory=True)
        else:
            # Replace atomically rather than modifying an existing inode (which
            # might have a hard link elsewhere). Keep failed temporary writes local.
            temporary = None
            try:
                with tempfile.NamedTemporaryFile(dir=path.parent, prefix=".harness-", delete=False) as stream:
                    temporary = Path(stream.name)
                    stream.write(wanted.data)
                temporary.chmod(0o644)
                temporary.replace(path)
            finally:
                if temporary is not None and temporary.exists():
                    temporary.unlink()


def merge_config(root, package, seeds=None):
    defaults = load_json(package / "defaults.json")
    project = json.loads(read_source(root, ".agents/project/config.json", seeds))
    keys = {"schema_version", "agents", "disabled_agents", "skills", "mcp_servers",
            "claude_settings", "codex_settings", "codex_hooks"}
    if not isinstance(project, dict) or set(project) != keys or project["schema_version"] != 1:
        raise ValueError("project/config.json must use the documented schema_version 1 fields")
    if defaults.get("schema_version") != 1:
        raise ValueError("unsupported framework defaults schema")
    if not isinstance(project["disabled_agents"], list):
        raise ValueError("disabled_agents must be a list")
    agents = {}
    for layer in (defaults["agents"], project["agents"]):
        seen = set()
        for agent in layer:
            name = agent["name"]
            if not isinstance(name, str) or not NAME.fullmatch(name) or name in seen:
                raise ValueError("agent names must be unique within a layer and lowercase hyphenated")
            seen.add(name)
            if set(agent) - {"name", "description", "instructions", "claude", "codex"}:
                raise ValueError(f"unknown agent fields: {name}")
            agents[name] = {**agents.get(name, {}), **agent}
    for name in project["disabled_agents"]:
        if name not in agents:
            raise ValueError(f"unknown disabled agent: {name}")
        del agents[name]
    result = {"agents": list(agents.values()), "skills": project["skills"]}
    for key in ("mcp_servers", "claude_settings", "codex_settings", "codex_hooks"):
        if not isinstance(project[key], dict):
            raise ValueError(f"{key} must be an object")
        # Native settings intentionally replace whole top-level keys, not merge
        # permission lists whose meaning differs between harnesses.
        result[key] = {**defaults[key], **project[key]}
    return result


def validate_skill(folder):
    path = folder / "SKILL.md"
    content = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\n(.*?)\n---\n", content, re.S)
    if not match:
        raise ValueError(f"{path}: missing YAML frontmatter")
    lines = match[1].splitlines()
    if len(lines) != 2:
        raise ValueError(f"{path}: portable frontmatter requires two single-line fields")
    metadata = {}
    for line in lines:
        field = re.fullmatch(r"(name|description): ([^\n]+)", line)
        if not field or field[1] in metadata:
            raise ValueError(f"{path}: portable frontmatter uses name and description only")
        raw = field[2]
        if raw.startswith('"'):
            value = json.loads(raw)
        elif raw.startswith("'") and raw.endswith("'"):
            value = raw[1:-1].replace("''", "'")
        else:
            ambiguous = {"true", "false", "null", "yes", "no", "on", "off"}
            if (not raw[0].isalpha() or raw.lower() in ambiguous or ": " in raw or
                    " #" in raw or "\t" in raw):
                raise ValueError(f"{path}: quote ambiguous YAML values using JSON strings")
            value = raw
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"{path}: empty or non-string metadata")
        metadata[field[1]] = value
    name = metadata.get("name", "")
    if name != folder.name or len(name) > 64 or not NAME.fullmatch(name):
        raise ValueError(f"{path}: invalid or mismatched skill name")
    if len(re.findall(r"^```[^\n]*$", content, re.M)) % 2:
        raise ValueError(f"{path}: unclosed code fence")
    validate_links(content, folder)


def validate_links(content, base, virtual=()):
    for target in re.findall(r"\]\(([^)]+)\)", content):
        if re.match(r"[a-zA-Z][a-zA-Z0-9+.-]*:", target) or target.startswith("#"):
            continue
        path = base / target.split("#", 1)[0].strip("<>")
        if not path.exists() and path not in virtual:
            raise ValueError(f"{base}: missing resource {target}")


def render(root, package=PACKAGE, seeds=None):
    config = merge_config(root, package, seeds)
    outputs = {}
    context = read_source(root, ".agents/project/context.md", seeds)
    instructions = (package / "instructions.md").read_text(encoding="utf-8")
    virtual = {root / p for p in (seeds or {})}
    validate_links(context, root, virtual)
    validate_links(instructions, root, virtual)
    docs = set((root / ".agents/project").glob("*.md")) | {
        root / p for p in (seeds or {}) if p.endswith(".md")}
    for doc in docs:
        if doc.name != "context.md":
            validate_links(read_source(root, doc.relative_to(root).as_posix(), seeds), doc.parent, virtual)
    if not (root / ".agents/project/index.md").is_file() and ".agents/project/index.md" not in (seeds or {}):
        raise ValueError("project knowledge index is required")
    outputs["AGENTS.md"] = text_entry(f"<!-- {MARKER} -->\n\n{instructions.rstrip()}\n\n{context.strip()}\n")
    outputs["CLAUDE.md"] = text_entry(f"# CLAUDE.md\n\n@AGENTS.md\n\n<!-- {MARKER} -->\n")
    for agent in config["agents"]:
        reference = agent["instructions"]
        parts = Path(reference).parts
        if len(parts) == 3 and parts[:2] == ("framework", "agents"):
            path = safe_path(package, "/".join(parts[1:]))
            if path.is_symlink():
                raise ValueError("agent instructions must not be symlinks")
            body = path.read_text(encoding="utf-8")
        elif len(parts) == 2 and parts[0] == "agents":
            body = read_source(root, ".agents/" + reference)
        else:
            raise ValueError("agent instructions must stay inside framework/agents or .agents/agents")
        body = body.strip() + "\n"
        if not body.strip() or not isinstance(agent["description"], str) or not agent["description"].strip():
            raise ValueError("agent instructions and description must not be empty")
        claude, codex = agent.get("claude", {}), agent.get("codex", {})
        if set(claude) - CLAUDE_FIELDS or set(codex) - CODEX_FIELDS:
            raise ValueError("unsupported agent override; extend and test the adapter first")
        common = {"name": agent["name"], "description": agent["description"]}
        yaml = "\n".join(f"{k}: {scalar(v)}" for k, v in {**common, **claude}.items())
        outputs[f".claude/agents/{agent['name']}.md"] = text_entry(
            f"---\n{yaml}\n---\n\n<!-- {MARKER} -->\n\n{body}")
        values = {**common, **codex, "developer_instructions": body}
        outputs[f".codex/agents/{agent['name']}.toml"] = text_entry(
            f"# {MARKER}\n" + "".join(f"{k} = {scalar(v)}\n" for k, v in values.items()))
    toml = [f"# {MARKER}\n"]
    settings = config["codex_settings"]
    if set(settings) - CODEX_SETTINGS:
        raise ValueError("unsupported Codex project setting; extend and test the adapter first")
    for key, value in settings.items():
        if key != "features":
            toml.append(f"{key} = {scalar(value)}\n")
    if "features" in settings:
        toml.append("\n[features]\n")
        for key, value in settings["features"].items():
            if not re.fullmatch(r"[a-z][a-z0-9_]*", key) or not isinstance(value, bool):
                raise ValueError("Codex features require boolean values and safe keys")
            toml.append(f"{key} = {scalar(value)}\n")
    for name, server in config["mcp_servers"].items():
        if not NAME.fullmatch(name) or set(server) != {"command", "args"}:
            raise ValueError("MCP definitions require a safe name, command, and args")
        if not isinstance(server["command"], str) or not server["command"]:
            raise ValueError("MCP command must be a nonempty string")
        if not isinstance(server["args"], list) or not all(isinstance(v, str) for v in server["args"]):
            raise ValueError("MCP args must be a string list")
        toml.append(f"\n[mcp_servers.{name}]\n")
        toml.extend(f"{key} = {scalar(value)}\n" for key, value in server.items())
    outputs[".codex/config.toml"] = text_entry("".join(toml))
    outputs[".mcp.json"] = text_entry(json_text({"mcpServers": config["mcp_servers"]}))
    outputs[".claude/settings.json"] = text_entry(json_text(config["claude_settings"]))
    if config["codex_hooks"]:
        if set(config["codex_hooks"]) != {"hooks"} or not isinstance(config["codex_hooks"]["hooks"], dict):
            raise ValueError("codex_hooks must be an empty object or a native hooks object")
        outputs[".codex/hooks.json"] = text_entry(json_text(config["codex_hooks"]))
    skills = config["skills"]
    if not isinstance(skills, list) or not all(isinstance(s, str) and NAME.fullmatch(s) for s in skills):
        raise ValueError("skills must be a list of framework skill names")
    if len(skills) != len(set(skills)):
        raise ValueError("duplicate framework skill names")
    for name in skills:
        validate_skill(package / "skills" / name)
        outputs[f".agents/skills/{name}"] = Entry(link=f"../framework/skills/{name}")
    skill_root = safe_path(root, ".agents/skills")
    if skill_root.is_symlink():
        raise ValueError(".agents/skills must be a real directory")
    for folder in sorted(skill_root.glob("*")):
        if folder.name in skills:
            continue
        if folder.is_symlink() and folder.readlink().as_posix() == f"../framework/skills/{folder.name}":
            # A formerly selected framework skill will be removed by the lock plan.
            continue
        if folder.is_dir():
            validate_skill(folder)
        elif folder.is_symlink():
            raise ValueError(f"broken skill symlink: {folder}")
    outputs[".claude/skills"] = Entry(link="../.agents/skills")
    return outputs


def sync_plan(root, package=PACKAGE):
    return plan_managed(root, render(root, package), GENERATED_LOCK, generated_path)


def package_files(package):
    required = {"harness.py", "README.md", "VERSION", "instructions.md", "defaults.json"}
    paths = [package / name for name in sorted(required)]
    for directory in ("agents", "skills", "templates", "tests"):
        paths.extend(p for p in sorted((package / directory).rglob("*"))
                     if p.is_file() and "__pycache__" not in p.parts and p.suffix != ".pyc")
    outputs = {}
    for path in paths:
        relative = path.relative_to(package).as_posix()
        if path.is_symlink() or any(p.is_symlink() for p in path.parents if p != package):
            raise ValueError(f"framework package must contain real files: {relative}")
        outputs[".agents/framework/" + relative] = Entry(data=path.read_bytes())
    return outputs


def install_plan(root, package=PACKAGE):
    if not root.is_dir():
        raise ValueError("target project must be an existing directory")
    core = package_files(package)
    changes = plan_managed(root, core, FRAMEWORK_LOCK, lambda p: p.startswith(".agents/framework/"))
    seeds = {}
    for path in sorted((package / "templates/project").glob("*")):
        relative = ".agents/project/" + path.name
        target = safe_path(root, relative)
        if target.is_symlink():
            raise ValueError(f"project source must not be a symlink: {relative}")
        if not target.exists():
            seeds[relative] = Entry(data=path.read_bytes())
    outputs = render(root, package, seeds)
    changes.update(plan_managed(root, outputs, GENERATED_LOCK, generated_path))
    changes.update(seeds)
    return changes


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("sync", "check"):
        item = sub.add_parser(command)
        item.add_argument("--root", type=Path, default=Path.cwd())
    installer = sub.add_parser("install", help="copy or explicitly upgrade this package in another project")
    installer.add_argument("--target", type=Path, required=True)
    installer.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    try:
        root = (args.target if args.command == "install" else args.root).resolve()
        changes = install_plan(root) if args.command == "install" else sync_plan(root)
        if args.command == "check":
            if changes:
                print("Out of date:\n" + "\n".join(sorted(changes)), file=sys.stderr)
                return 1
            print("Harness configuration and knowledge links are consistent.")
        elif args.command == "install" and args.dry_run:
            print("Planned changes (no files written):\n" + "\n".join(sorted(changes)))
        else:
            apply_plan(root, changes)
            print(f"{args.command}: updated {len(changes)} managed or initial files.")
        return 0
    except (OSError, ValueError, KeyError, TypeError, AttributeError) as error:
        print(f"harness: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
