// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	bizauth "auth_info/internal/biz/auth"
	bizdict "auth_info/internal/biz/dict"
	bizdoc "auth_info/internal/biz/document"
	bizhello "auth_info/internal/biz/hello"
	"auth_info/internal/config"
	"auth_info/internal/data"
	"auth_info/internal/handler"
	"auth_info/internal/service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, error) {
	db, err := data.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	enforcer, err := data.NewEnforcer(db, cfg)
	if err != nil {
		return nil, err
	}
	authUseCase := bizauth.NewUseCase(db, cfg)
	helloUseCase := bizhello.NewUseCase()
	dictUseCase := bizdict.NewUseCase(db)
	documentUseCase := bizdoc.NewUseCase()
	helloHandler := handler.NewHelloHandler(helloUseCase)
	authHandler := handler.NewAuthHandler(authUseCase)
	dictHandler := handler.NewDictHandler(dictUseCase)
	documentHandler := handler.NewDocumentHandler(documentUseCase)
	helloService := service.NewHelloService(helloUseCase)
	application, err := NewApp(cfg, authUseCase, enforcer, helloHandler, authHandler, helloService, dictHandler, documentHandler)
	if err != nil {
		return nil, err
	}
	return application, nil
}
