// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"auth_info/internal/config"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, error) {
	app, err := NewApp(cfg)
	if err != nil {
		return nil, err
	}
	return app, nil
}
