// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	auth2 "auth_info/internal/biz/auth"
	dict2 "auth_info/internal/biz/dict"
	"auth_info/internal/biz/hello"
	"auth_info/internal/config"
	"auth_info/internal/data"
	"auth_info/internal/data/auth"
	"auth_info/internal/data/dict"
	auth3 "auth_info/internal/handler/auth"
	dict3 "auth_info/internal/handler/dict"
	hello2 "auth_info/internal/handler/hello"
	"auth_info/internal/mcpserver"
	"auth_info/internal/server"
	hello3 "auth_info/internal/service/hello"
)

// Injectors from wire.go:

func initializeApp(cfg *config.Config, resources *Lifecycle) (*App, error) {
	logger, err := ProvideLogger(cfg, resources)
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(cfg, logger, resources)
	if err != nil {
		return nil, err
	}
	userRepo := auth.NewUserRepository(db)
	options := ProvideAuthOptions(cfg)
	useCase := auth2.NewUseCase(userRepo, options, logger)
	enforcer, err := data.NewEnforcer(db, cfg, logger)
	if err != nil {
		return nil, err
	}
	helloUseCase := hello.NewUseCase(logger)
	handler := hello2.NewHandler(helloUseCase)
	authHandler := auth3.NewHandler(useCase)
	httpHandler := mcpserver.NewHelloMCPHandler(helloUseCase)
	dictRepo := dict.NewDictRepository(db)
	dictUseCase := dict2.NewUseCase(dictRepo, logger)
	dictHandler := dict3.NewHandler(dictUseCase)
	httpDeps := server.HTTPDeps{
		AuthUC:          useCase,
		Enforcer:        enforcer,
		HelloHandler:    handler,
		AuthHandler:     authHandler,
		HelloMCPHandler: httpHandler,
		DictHandler:     dictHandler,
	}
	httpServer, err := server.NewHTTPServer(cfg, logger, httpDeps)
	if err != nil {
		return nil, err
	}
	service := hello3.NewService(helloUseCase)
	grpc := server.NewGRPCServer(cfg, logger, service)
	app, err := NewApp(cfg, logger, httpServer, grpc, resources)
	if err != nil {
		return nil, err
	}
	return app, nil
}
